CREATE TABLE "usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "email" varchar UNIQUE,
  "senha" varchar
);

CREATE TABLE "tarefa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar,
  "descricao" text,
  "status" varchar,
  "data_desejada" date,
  "data_limite" date,
  "importancia" int,
  "progresso" int,
  "usuario_id" int,
  "categoria_id" int,
  "origem_id" int
);

CREATE TABLE "categoria" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "prioridade" int
);

CREATE TABLE "origem" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "relevancia" int
);

CREATE TABLE "agenda" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tarefa_id" int,
  "data_inicio" timestamp,
  "data_fim" timestamp,
  "anotacoes" text
);

ALTER TABLE "tarefa" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id");

ALTER TABLE "tarefa" ADD FOREIGN KEY ("categoria_id") REFERENCES "categoria" ("id");

ALTER TABLE "tarefa" ADD FOREIGN KEY ("origem_id") REFERENCES "origem" ("id");

ALTER TABLE "agenda" ADD FOREIGN KEY ("tarefa_id") REFERENCES "tarefa" ("id");
